### ISSUE TITLE
multiple instances bug

### ISSUE THREAD

**Issue by rvencu** [andyvr/water-ripple#1]
Hi, when I create multiple instances if I set the onclick to true, after activating a number of instances with the ripple, going back to click on old objects only reactivates the ripples on the last instance

**Comment by euland** [comment]
HI this java it's so nice :) i'm not really into coding in java but just looking and try to understand another way, but i think it works pretty well !

I just create this simple html graphic layers for personal diary http://acquar.io/0h/index.html
and i'd like to add the effect on more images in the html, how can i do that ? 

i tied to do a second class but really i'm not that far to get how to get more function in the sript... can someone help me ? :)

**Comment by andyvr** [comment]
The plugin was not working correctly with multiple images. This has been fixed.
Please re-download the plugin.
